### ISSUE TITLE
Hazelcast client auto discovery in AWS Fargate

### ISSUE THREAD

**Issue by ssi-hu-miklos-kosarkar** [hazelcast/hazelcast-aws#204]
Hi,

I have a question about hazelcast-client setup in aws fargate.
It's not clear to me if my cluster has to have public ip or not even if my client is inside aws.

```
hazelcast-client:
  network:
    aws:
      enabled: true
      cluster: name-of-my-cluster
      security-group-name: name-of-my-security-group
      use-public-ip: false
```

This exception message was logged at some point: Failed to configure discovery strategies.

Maybe my understanding of a client is wrong.

I don't want to have public ip for the hazelcast cluster.
Can the client use auto discovery or is there something else I could use to connect to the cluster?
